import { UserModel } from '../shared/models/user.model';

// User mocks
export const USERS: UserModel[] = [{
    Id: 1,
    Firstname: 'Nathan',
    Lastname: 'Fox',
    Fullname: 'Nathan Fox',
    Initials: 'NF',
    UserName: 'nathanfox',
    Email: 'nathanfox@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-07.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 2,
    Firstname: 'Priscilla',
    Lastname: 'James',
    Fullname: 'Priscilla James',
    Initials: 'PJ',
    UserName: 'priscillajames',
    Email: 'priscillajames@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-08.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 3,
    Firstname: 'Jenet',
    Lastname: 'White',
    Fullname: 'Jenet White',
    Initials: 'JW',
    UserName: 'jenetwhite',
    Email: 'jenetwhite@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-09.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 4,
    Firstname: 'John',
    Lastname: 'Smith',
    Fullname: 'John Smith',
    Initials: 'JS',
    UserName: 'johnsmith',
    Email: 'johnsmith@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-11.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 5,
    Firstname: 'Tony',
    Lastname: 'Nicole',
    Fullname: 'Tony Nicole',
    Initials: 'TN',
    UserName: 'tonynicole',
    Email: 'tonynicole@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-12.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 6,
    Firstname: 'Vanesa',
    Lastname: 'Sinclar',
    Fullname: 'Vanesa Sinclar',
    Initials: 'VS',
    UserName: 'vanesasinclar',
    Email: 'vanesasinclar@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-10.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 7,
    Firstname: 'Adam',
    Lastname: 'Young',
    Fullname: 'Adam Young',
    Initials: 'AY',
    UserName: 'adamyoung',
    Email: 'adamyoung@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-06.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 8,
    Firstname: 'Valerie',
    Lastname: 'Berg',
    Fullname: 'Valerie Berg',
    Initials: 'VB',
    UserName: 'valerieberg',
    Email: 'valerieberg@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-13.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 9,
    Firstname: 'Joshua',
    Lastname: 'Gordon',
    Fullname: 'Joshua Gordon',
    Initials: 'JG',
    UserName: 'joshuagordon',
    Email: 'joshuagordon@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-04.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 9,
    Firstname: 'Anthony',
    Lastname: 'Jones',
    Fullname: 'Anthony Jones',
    Initials: 'AJ',
    UserName: 'anthonyjones',
    Email: 'anthonyjones@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-01.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 10,
    Firstname: 'Isabel',
    Lastname: 'Holmes',
    Fullname: 'Isabel Holmes',
    Initials: 'IH',
    UserName: 'isabelholmes',
    Email: 'isabelholmes@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-15.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
},
{
    Id: 11,
    Firstname: 'Emily',
    Lastname: 'Lawrence',
    Fullname: 'Emily Lawrence',
    Initials: 'EL',
    UserName: 'emilylawrence',
    Email: 'emilylawrence@mail.com',
    Avatar: '../../../assets/images/avatars/avatar-03.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
}];

export const CURRENT_USER: UserModel = {
    Id: 12,
    Firstname: 'Ashton',
    Lastname: 'Colon',
    Fullname: 'Ashton Colon',
    Initials: 'AC',
    UserName: 'ashtoncolon',
    Email: 'ashtoncolon@gmail.com',
    Avatar: '../../../assets/images/avatars/avatar-14.png',
    Bio: '',
    Active: true,
    Token: '',
    Password: ''
};
